version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=secgeodb
      - DB_USER=secgeouser
      - DB_PASS=secgeopass
      - DEBUG=1
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=secgeodb
      - POSTGRES_USER=secgeouser
      - POSTGRES_PASSWORD==secgeopass


volumes:
  dev-db-data:
  